[package]
name = "gene-utils"
edition.workspace = true
keywords.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
version.workspace = true
authors.workspace = true

[dependencies]
clap = { version = "4.4.10", features = ["derive"] }
